### ISSUE TITLE
Unmatched files are ignored

### ISSUE THREAD

**Issue by adriantre** [microsoft/torchgeo#1452]
https://github.com/microsoft/torchgeo/blob/c622c5cf5fabd8ab9527a4c7a782efb157ff34ed/torchgeo/datasets/geo.py#L367C21-L367C21

https://github.com/microsoft/torchgeo/blob/c622c5cf5fabd8ab9527a4c7a782efb157ff34ed/torchgeo/datasets/geo.py#L385

Log user warning both places? Is also the case in VectorDataset.

**Comment by adamjstewart** [comment]
Most regexes have no file extension so that any possible file type can be matched. The result of this is that glob will frequently pick up auxiliary and metadata files, attempt to read them, and skip them. If we logged all of the skipped matches, you would be drowning in innocuous warnings.

This also relates to #139

**Comment by adriantre** [comment]
Oh yes, I see the problem now. I'm coming from the mindset of user specified list-of-files, of which I would want to be notified if I passed something that is not valid. But now I see the problem.

**Comment by adamjstewart** [comment]
Should we keep this issue open? It's unclear what the ideal behavior or correct resolution should be.

**Comment by adriantre** [comment]
Can reopen if users report that they find the current behaviour annoying.
