### ISSUE TITLE
Error in main readme: we provide train.py and evaluate.py scripts to train and evaluate

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/torchgeo#1626]
### Issue

In [Reproducibility with Lightning](https://github.com/microsoft/torchgeo/tree/7faf0bb49a2696887f77f86d63deb0cec6e7e045#reproducibility-with-lightning) it states `we provide train.py and evaluate.py scripts to train and evaluate` but as far as I can see these files do not exist. The correct instructions are in the [v0.5.0](https://github.com/microsoft/torchgeo/releases/tag/v0.5.0) release notes.

I [also spotted](https://github.com/search?q=repo%3Amicrosoft%2Ftorchgeo+train.py&type=code) reference to `train.py` in a few experiments, and that may require updating.

### Fix

Wanted to check my understanding before making a PR

**Comment by adamjstewart** [comment]
Correct, the new `torchgeo` (or `python -m torchgeo`) script is the replacement for `train.py`.

I also noted this in #1196. We should probably copy that whole section of the release notes to the README, as the CLI isn't documented at all right now.

Feel free to submit a PR to add just the script stuff or all of #1196. Otherwise I'll definitely get to it before the next patch release.
