### ISSUE TITLE
Add YAML formatter

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/torchgeo#2004]
### Summary

We should add a YAML formatter to CI

### Rationale

Indentation is inconsistent, and I frequently have to remind people to add EOL chars before EOF chars.

### Implementation

Bunch of options:

* [yamlfmt](https://github.com/google/yamlfmt)
* [yamlfix](https://github.com/lyz-code/yamlfix)
* [prettier](https://github.com/prettier/prettier)
* [pretty-yaml](https://github.com/mk-fg/pretty-yaml)
* and many more

**Comment by Domejko** [comment]
Hey @adamjstewart 

I can take care of this. 

I assume that formatting should be run on all files, not just some specific folder ?  Also to clarify, this job should be implemented in style.yaml CI ?

**Comment by adamjstewart** [comment]
Yes, all `*.yaml` and `*.yml` files.

Yes, `.github/workflows/style.yaml`.

It would be preferable to use something available on PyPI so we can explicitly list it as a dependency and install it with pip. Maybe you can review the options and propose which tool is best and why before actually making any code changes?

**Comment by Domejko** [comment]
From what I have searched [Google (unofficial) yamlfmt](https://github.com/google/yamlfmt) if well recommended but it's written in `Go` and it's not in PyPI, it is similar with [Prettier](https://github.com/prettier/prettier) that can cover not only YAML but many other formats as well but it needs different package managers like NPM, Yarn etc.

In this case I would decide on [yamlfix](https://github.com/lyz-code/yamlfix). It's available on PyPI, have good and clear [documentation](https://lyz-code.github.io/yamlfix/) can be simply configured in `pyproject.toml` if additional options are needed. Is maintained and updated since few years so it doesn't look like dead project.

**Comment by adamjstewart** [comment]
yamlfmt's dependency on go and prettier's dependency on npm are unideal.

yamlfix appears to be somewhat dead: https://github.com/lyz-code/yamlfix/issues/272

What about pretty-yaml? Are there any other alternatives we can consider?

**Comment by Domejko** [comment]
True, sorry I haven't noticed that.

[Pretty-yaml](https://github.com/mk-fg/pretty-yaml) is very simple and seams to not support going thru all the directories in search for `*.yaml`, `*.yml` files. On top of that it's replacing `true` with `yes` and `false` with `no`. So it doesn't suet our needs.

I will be keep on searching and wil let you know as soon as I find something.

**Comment by adamjstewart** [comment]
In YAML, `true` == `yes`: https://yaml.org/type/bool.html

I personally prefer `true`, but I do want to ensure that all Booleans follow the same pattern.

**Comment by adamjstewart** [comment]
Let me think about this. It might not be horrible to use a go/npm package since it's only used by developers, not users. I'm also curious how many files would be changed if we used something like prettier. We do need something for JSON files too for .ipynb files...

**Comment by Domejko** [comment]
When it's a part of CI it don't make much of a difference to us, it's just matter of using `actions/setup-node@v4` or `actions/setup-go@v5` instead of `actions/setup-python@v5`. On the other hand Prettier could be also used as [pre-commit hook](https://prettier.io/docs/en/precommit) but then of course node would had to be installed with Prettier as dependency.

It's possible that initially it could slightly change all the files since it's very opinionated, as it's devs say *"Prettier is not a kitchen-sink code formatter that attempts to print your code in any way you wish. It is opinionated."*. But still it have some options that can be always adjusted. If JSON files also would had to be handled then Prettier is a best choice.

**Comment by adamjstewart** [comment]
I'm fine with opinionated, that's the whole point of a formatter/linter.

**Comment by Domejko** [comment]
What is the final decision on that matter ? Will we use Prettier ?

**Comment by adamjstewart** [comment]
I think prettier is probably best. Can you open a PR that uses prettier to see what the changes look like?

**Comment by Domejko** [comment]
This is how it looks like while it was run without any additional options with just `npx prettier . --write`

**Comment by Domejko** [comment]
Have you seen changes in PR #2018 ?

**Comment by adamjstewart** [comment]
Seen yes, but haven't had time to review in detail yet. Apologies for the wait...
