### ISSUE TITLE
Installation via conda raises ResolvePackageNotFound on Windows. Two conda channels missing for a fix.

### ISSUE THREAD

**Issue by remtav** [microsoft/torchgeo#527]
On Windows (10), conda can't find torchvision nor pycocotools: 
```
(base) C:\Users\...>conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - torchvision[version='>=0.10']
  - pycocotools
```
Adding `pytorch` and `esri` in [channels of environment.yml](https://github.com/microsoft/torchgeo/blob/main/environment.yml#L2) seems to fix this issue.

**Comment by adamjstewart** [comment]
Yes, the PyTorch recipe for conda-forge [does not support Windows](https://github.com/conda-forge/pytorch-cpu-feedstock/blob/main/recipe/meta.yaml#L16). Note that it can be dangerous to mix channels because conda does not ensure ABI compatibility, and conda-forge [explicitly recommends against mixing channels](https://conda-forge.org/docs/user/tipsandtricks.html). For this reason, our `environment.yml` only uses `conda-forge` and not any other channels.

My personal suggestion would be to avoid using conda or to avoid using Windows. [Spack](https://spack.io) has superior ABI compatibility because it builds everything from source, although [Windows support is still experimental](https://spack.readthedocs.io/en/latest/getting_started.html#spack-on-windows). On Windows, you can install Linux via WSL and do things in Linux instead. Pip has also gotten surprisingly good now that most packages have wheels, although fiona/rasterio still don't have Windows wheels and require conda to install.

Hope this helps! Sorry I don't have a better answer.

**Comment by weiji14** [comment]
Related issues: https://github.com/conda-forge/torchvision-feedstock/pull/23 and https://github.com/conda-forge/pycocotools-feedstock/issues/16. Might pay to see if we can push on those issues/PRs to get resolved in conda-forge directly.

**Comment by remtav** [comment]
oups just opened a PR after seing your reponse @adamjstewart. I'll close and resolve on my side. I thought this could be useful for other windows users (and without consequence for linux users). I'll look into WSL and Spack.

I've been mixing conda channels for a while and never had trouble. Maybe mixing conda-forge with the defaults channel (as is mentionned in the referenced link) causes more problems than other mixes. If the good practice is explicitely defined for not using multiple channels, then be it. However, I can hardly see how one can use a single channel for all purposes. For example, Pytorch points to [its "pytorch" conda channel ](https://pytorch.org/get-started/locally/) for installation of pytorch, torchvision, etc.

**Comment by isaaccorley** [comment]
+1 for WSL. It's gotten better over time and VSCode has a nice Remote WSL extension. It also supports access to CUDA devices directly now so you can train on your GPU.

**Comment by adamjstewart** [comment]
> I've been mixing conda channels for a while and never had trouble. Maybe mixing conda-forge with the defaults channel (as is mentionned in the referenced link) causes more problems than other mixes.

That could very well be the case. If someone can confirm that #528 doesn't cause issues on macOS or Linux then I would be fine with merging that kind of solution. I just get the impression that if you run into any kind of issues like that, the first thing the developers will say is to avoid mixing channels.

**Comment by remtav** [comment]
@adamjstewart I can confirm the conda environment creation from #528 works on Ubuntu 20.04. It does raise a "pip subprocess error" but that's also the case with current environment.yml:
```
Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/pytorch/pytorch_sphinx_theme /tmp/pip-req-build-g89ucqfc
ERROR: Could not find a version that satisfies the requirement open3d>=0.11.2 (from versions: none)
ERROR: No matching distribution found for open3d>=0.11.2

failed

CondaEnvException: Pip failed
```
Commands from [installation instructions](https://torchgeo.readthedocs.io/en/latest/user/installation.html#id2) succeed however:
```
conda activate torchgeo
pip install .
```

**Comment by adamjstewart** [comment]
Yeah, that's another complaint I have with conda, there's no way to expression "optional" dependencies. Open3D isn't necessary for 99% of users but we have no way to express that. If adding an extra channel solves the issue then that could be a good solution. Want to reopen #528 and add that?
