### ISSUE TITLE
Deciding on "masks" or "mask" in `__getitem__`

### ISSUE THREAD

**Issue by calebrob6** [microsoft/torchgeo#61]
The `__getitem__` methods in Chesapeake and CDL datasets return a key "masks" while SEN12MS and LandcoverAI return "mask". Should we choose one or is there some reason we need to differentiate?

**Comment by adamjstewart** [comment]
If we end up using Kornia, we'll have to use their standard dict key names (https://kornia.readthedocs.io/en/latest/augmentation.container.html#augmentation-sequential): “input”, “mask”, “bbox”, “bbox_xyxy”, “bbox_xywh”, “keypoints”

**Comment by isaaccorley** [comment]
I agree with using kornia's standard, however this is a tough one because even [PyTorch's detection/segmentation models](https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html) expect a target dict with "masks", "boxes", "labels", etc. We may just have to pick what we think is best and then guide the user to make wrappers to work with whatever format their model expects.

**Comment by adamjstewart** [comment]
That's part of the reason that some of the code uses "masks" instead of "mask". I think that's not a requirement of the model, just a requirement for the transforms they define in their reference code. The models just take an input image and mask.

**Comment by isaaccorley** [comment]
Their MaskRCNN model in the example requires a forward pass `model(x, target)` where target is a dict of "boxes", "labels", and "masks" but that might be unique to their RCNN models. I think you're right though for their semantic segmentation models.
