### ISSUE TITLE
Transfer static fields from GeoDataset(& others) to init method to allow overiding defaults for dynamic use

### ISSUE THREAD

**Issue by kleffy** [microsoft/torchgeo#797]
I want to be able to define one custom dataset class that loads similar data from different sources.

```python
l1a_root = r'datasets/L1A_Arcachon'
l1a_filename_glob = r"L1A-DT000400126_20170218T110119Z_003_V000204_20200512T142942Z-SPECTRAL_IMAGE.TIF"

l2a_root = r'datasets/L2A_Arcachon'
l2a_filename_glob = r"L2A-DT000400126_20170218T110119Z_003_V000204_20200512T142942Z-SPECTRAL_IMAGE.TIF"

ds_1A = EnmapDataset(root=l1a_root, filename_glob=l1a_fn)
ds_2A = EnmapDataset(root=l2a_root, filename_glob=l2a_fn)
```

At the moment, I will have to go inside the custom class to change static fields for every file from a different source or worst case duplicate the same class. For example.

```python
l1a_root = r'datasets/L1A_Arcachon'
l1a_filename_glob = r"L1A-DT000400126_20170218T110119Z_003_V000204_20200512T142942Z-SPECTRAL_IMAGE.TIF"

l2a_root = r'datasets/L2A_Arcachon'
l2a_filename_glob = r"L2A-DT000400126_20170218T110119Z_003_V000204_20200512T142942Z-SPECTRAL_IMAGE.TIF"

ds_1A = EnmapDataset_1A(root=l1a_root)
ds_2A = EnmapDataset_2A(root=l2a_root)
```

Please, if anyone knows a better approach to achieving the result above, kindly leave a comment.

**Comment by adamjstewart** [comment]
There are actually a couple of ways to achieve the behavior you want. 

### Override class attributes with instance attributes

To get the first behavior:
```python
ds_1A = EnmapDataset(root=l1a_root, filename_glob=l1a_fn)
ds_2A = EnmapDataset(root=l2a_root, filename_glob=l2a_fn)
```
you could override the `__init__` method to allow overriding class attributes with instance attributes:
```python
class EnmapDataset(RasterDataset):
    def __init__(self, filename_glob, *args, **kwargs):
        self.filename_glob = filename_glob
        super().__init__(*args, **kwargs)
```
This way, you only have a single class, and can change `filename_glob` on the fly.

### Subclasses

To get the second behavior:
```python
ds_1A = EnmapDataset_1A(root=l1a_root)
ds_2A = EnmapDataset_2A(root=l2a_root)
```
you could use subclasses:
```python
class EnmapDataset_1A(EnmapDataset):
    filename_glob = "L1A-*"

class EnmapDataset_2A(EnmapDataset):
    filename_glob = "L2A-*"
```
This way, all common logic can be in the `EnmapDataset` base class, so you don't need to duplicate any logic.

Of course, we could also do this at the `RasterDataset` level like you suggest, but first I want to see if one of the above suggestions is good enough for you. I like the current approach because we can quickly create new datasets by only overriding a couple class attributes.

**Comment by kleffy** [comment]
Dear Adam,

I hope this email meets you well.

Thank you for your response and suggestions.

Your suggestions work fine for me. I guess there is no need to implement my
suggestions then.

Thank you.

Best Regards,
Daniel
